import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

// Prisma v7: datasource URL must be in prisma.config.ts or provided via DATABASE_URL env
// The prisma.config.ts already reads from DATABASE_URL
const prisma = new PrismaClient()


async function main() {
  console.log('🌱 Seeding MLAKOOW database...')

  // Categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'alam' },
      update: {},
      create: { name: 'Alam', slug: 'alam', icon: '🌿', color: '#10B981' },
    }),
    prisma.category.upsert({
      where: { slug: 'budaya' },
      update: {},
      create: { name: 'Budaya', slug: 'budaya', icon: '🎭', color: '#F59E0B' },
    }),
    prisma.category.upsert({
      where: { slug: 'kuliner' },
      update: {},
      create: { name: 'Kuliner', slug: 'kuliner', icon: '🍜', color: '#EF4444' },
    }),
    prisma.category.upsert({
      where: { slug: 'sejarah' },
      update: {},
      create: { name: 'Sejarah', slug: 'sejarah', icon: '🏛️', color: '#3B82F6' },
    }),
    prisma.category.upsert({
      where: { slug: 'keluarga' },
      update: {},
      create: { name: 'Keluarga', slug: 'keluarga', icon: '👨‍👩‍👧', color: '#EC4899' },
    }),
    prisma.category.upsert({
      where: { slug: 'hidden-gem' },
      update: {},
      create: { name: 'Hidden Gem', slug: 'hidden-gem', icon: '💎', color: '#7C3AED' },
    }),
  ])

  const [alam, budaya, kuliner, sejarah, keluarga, hiddenGem] = categories
  console.log('✅ Categories seeded')

  // Admin user
  const hashedPassword = await bcrypt.hash('admin123', 12)
  await prisma.user.upsert({
    where: { email: 'admin@mlakoow.com' },
    update: {},
    create: {
      name: 'Admin MLAKOOW',
      email: 'admin@mlakoow.com',
      password: hashedPassword,
      role: 'admin',
    },
  })

  // Demo user
  const demoPassword = await bcrypt.hash('demo123', 12)
  await prisma.user.upsert({
    where: { email: 'demo@mlakoow.com' },
    update: {},
    create: {
      name: 'Wisatawan Demo',
      email: 'demo@mlakoow.com',
      password: demoPassword,
      role: 'user',
    },
  })
  console.log('✅ Users seeded')

  // DESTINATIONS — 25 destinasi Surabaya
  const destinations = [
    // ===== SURABAYA UTARA =====
    {
      name: 'Kota Lama Surabaya',
      slug: 'kota-lama-surabaya',
      description: 'Kawasan bersejarah yang menyimpan jejak kolonial Belanda dengan bangunan-bangunan tua bergaya art deco yang megah. Kota Lama Surabaya adalah destinasi wajib bagi pecinta sejarah dan fotografi arsitektur. Jalan-jalan sempit berbatu, gedung-gedung tua yang terawat, dan suasana nostalgia membuat kawasan ini menjadi permata wisata budaya Surabaya.',
      categoryId: sejarah.id,
      area: 'Surabaya Utara',
      address: 'Jl. Kembang Jepun, Bongkaran, Surabaya Utara',
      lat: -7.2272,
      lng: 112.7327,
      openHour: '08:00',
      closeHour: '22:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1555217851-6141535bd771?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1561495376-dc9c7c5b8726?w=600&q=80',
        'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80',
      ]),
      rating: 4.7,
      reviewCount: 328,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 120,
      facilities: JSON.stringify(['Parkir', 'Toilet Umum', 'Kafe & Restoran', 'Galeri Seni', 'Toko Souvenir']),
    },
    {
      name: 'Masjid Ampel (Makam Sunan Ampel)',
      slug: 'masjid-ampel-sunan-ampel',
      description: 'Destinasi religi dan wisata budaya yang sangat penting di Surabaya. Makam Sunan Ampel, salah satu Wali Songo, menjadi tujuan ziarah dari seluruh Indonesia. Kawasan Ampel dikelilingi pasar Arab yang menjual berbagai produk khas Timur Tengah, kurma, parfum, dan batik Araber. Suasana spiritual dan multikultural yang kental menjadikan Ampel pengalaman wisata yang tak terlupakan.',
      categoryId: budaya.id,
      area: 'Surabaya Utara',
      address: 'Jl. Ampel Masjid No.53, Ampel, Semampir, Surabaya',
      lat: -7.2350,
      lng: 112.7427,
      openHour: '05:00',
      closeHour: '22:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=800&q=80',
      gallery: JSON.stringify(['https://images.unsplash.com/photo-1604014137968-03abe2a03f7e?w=600&q=80']),
      rating: 4.8,
      reviewCount: 512,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 90,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Pasar Souvenir', 'Restoran Arab', 'Area Ziarah']),
    },
    {
      name: 'Jembatan Merah',
      slug: 'jembatan-merah-surabaya',
      description: 'Jembatan ikonik yang menjadi simbol perjuangan Arek-Arek Suroboyo pada pertempuran 10 November 1945. Bangunan bersejarah ini berdiri megah di atas Kali Mas dengan warna merah mencolok yang menjadi landmark Surabaya. Area sekitar Jembatan Merah kini berkembang menjadi kawasan wisata sejarah dengan berbagai gedung-gedung tua bersejarah.',
      categoryId: sejarah.id,
      area: 'Surabaya Utara',
      address: 'Jl. Kembang Jepun, Bongkaran, Surabaya',
      lat: -7.2297,
      lng: 112.7363,
      openHour: '00:00',
      closeHour: '23:59',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1519924211476-8948f3fb7faf?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.5,
      reviewCount: 198,
      featured: false,
      hiddenGem: false,
      estimatedDuration: 45,
      facilities: JSON.stringify(['Parkir Tepi Jalan', 'Warung Makan']),
    },
    {
      name: 'Pelabuhan Tanjung Perak',
      slug: 'pelabuhan-tanjung-perak',
      description: 'Pelabuhan terbesar di Surabaya yang bersejarah sebagai pintu masuk utama Jawa Timur sejak masa kolonial. Area wisata sekitar pelabuhan menawarkan pemandangan kapal-kapal besar, aktivitas kesibukan pelabuhan, dan sunset yang menakjubkan di atas air. Terminal penumpang lama yang kini menjadi kawasan wisata heritage menambah daya tarik lokasi ini.',
      categoryId: sejarah.id,
      area: 'Surabaya Utara',
      address: 'Jl. Perak Timur, Perak Timur, Pabean Cantian, Surabaya',
      lat: -7.1975,
      lng: 112.7302,
      openHour: '06:00',
      closeHour: '18:00',
      ticketPrice: 15000,
      mainImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.2,
      reviewCount: 145,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 60,
      facilities: JSON.stringify(['Parkir', 'Warung', 'Area Foto']),
    },

    // ===== SURABAYA PUSAT =====
    {
      name: 'Museum Kapal Selam (Monkasel)',
      slug: 'museum-kapal-selam-monkasel',
      description: 'Monumen dan museum unik berupa kapal selam asli KRI Pasopati 410 yang kini berada di darat sebagai objek wisata. Pengunjung dapat masuk ke dalam kapal selam dan melihat ruang-ruang dalam kapal yang autentik. Berlokasi di tepi Sungai Kalimas, Monkasel menjadi salah satu ikon wisata Surabaya yang wajib dikunjungi, terutama bagi penggemar sejarah militer.',
      categoryId: sejarah.id,
      area: 'Surabaya Pusat',
      address: 'Jl. Pemuda No.39, Embong Kaliasin, Genteng, Surabaya',
      lat: -7.2640,
      lng: 112.7431,
      openHour: '08:00',
      closeHour: '22:00',
      ticketPrice: 15000,
      mainImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1559827260-dc66d52bef47?w=600&q=80',
      ]),
      rating: 4.6,
      reviewCount: 412,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 90,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Kafe', 'Souvenir Shop', 'Area Bermain Anak']),
    },
    {
      name: 'Taman Bungkul',
      slug: 'taman-bungkul',
      description: 'Taman kota terbaik di Surabaya yang telah meraih penghargaan internasional sebagai taman terbaik di Asia. Taman Bungkul menjadi ruang publik aktif yang ramai setiap hari dengan berbagai aktivitas: skateboarding, jogging, kuliner, dan live music di akhir pekan. Makam Sunan Bungkul yang ada di dalam area menambah nilai historis dan spiritual tempat ini.',
      categoryId: alam.id,
      area: 'Surabaya Selatan',
      address: 'Jl. Raya Darmo, Darmo, Wonokromo, Surabaya',
      lat: -7.2987,
      lng: 112.7348,
      openHour: '06:00',
      closeHour: '22:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&q=80',
      ]),
      rating: 4.7,
      reviewCount: 687,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 90,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Wifi Gratis', 'Skateboarding Area', 'Warung & Kuliner', 'Area Bermain', 'Jogging Track']),
    },
    {
      name: 'Gedung Grahadi',
      slug: 'gedung-grahadi',
      description: 'Salah satu gedung bersejarah paling megah di Surabaya yang dibangun pada abad ke-18 masa pemerintahan Belanda. Gedung dengan arsitektur Neo-Klasik ini kini berfungsi sebagai kediaman resmi Gubernur Jawa Timur. Eksteriornya yang megah dengan halaman luas menjadi spot foto favorit wisatawan dan merupakan landmark utama Kota Surabaya.',
      categoryId: sejarah.id,
      area: 'Surabaya Pusat',
      address: 'Jl. Gubernur Suryo No.7, Embong Kaliasin, Genteng, Surabaya',
      lat: -7.2641,
      lng: 112.7386,
      openHour: '07:00',
      closeHour: '19:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1561495376-dc9c7c5b8726?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.4,
      reviewCount: 156,
      featured: false,
      hiddenGem: false,
      estimatedDuration: 30,
      facilities: JSON.stringify(['Parkir Tepi Jalan', 'Area Foto']),
    },
    {
      name: 'Tugu Pahlawan',
      slug: 'tugu-pahlawan',
      description: 'Monumen setinggi 41,15 meter yang dibangun untuk mengenang perjuangan Arek-Arek Suroboyo dalam pertempuran 10 November 1945. Monumen ikonik ini berdiri gagah di pusat kota Surabaya dan dilengkapi dengan Museum Sepuluh Nopember yang menyimpan berbagai koleksi benda bersejarah. Wajib dikunjungi saat Hari Pahlawan untuk merasakan suasana patriotisme.',
      categoryId: sejarah.id,
      area: 'Surabaya Pusat',
      address: 'Jl. Pahlawan, Alun-Alun Contong, Bubutan, Surabaya',
      lat: -7.2469,
      lng: 112.7378,
      openHour: '07:00',
      closeHour: '17:00',
      ticketPrice: 5000,
      mainImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.6,
      reviewCount: 523,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 75,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Museum', 'Taman', 'Souvenir']),
    },

    // ===== SURABAYA TIMUR =====
    {
      name: 'Pantai Kenjeran',
      slug: 'pantai-kenjeran',
      description: 'Pantai ikonik di Surabaya Timur yang menawarkan pemandangan laut dengan pemandangan Jembatan Suramadu di kejauhan. Kawasan Kenjeran terdiri dari Kenjeran Park dan area pesisir dengan perkampungan nelayan tradisional. Saat sore hari, sunset di Kenjeran menjadi daya tarik utama yang sayang dilewatkan. Tersedia berbagai kuliner seafood segar langsung dari nelayan.',
      categoryId: alam.id,
      area: 'Surabaya Timur',
      address: 'Jl. Kenjeran, Sukolilo, Surabaya',
      lat: -7.2286,
      lng: 112.8057,
      openHour: '06:00',
      closeHour: '21:00',
      ticketPrice: 10000,
      mainImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=600&q=80',
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
      ]),
      rating: 4.3,
      reviewCount: 456,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 120,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Warung Seafood', 'Penyewaan Perahu', 'Taman Bermain']),
    },
    {
      name: 'Kebun Binatang Surabaya (KBS)',
      slug: 'kebun-binatang-surabaya',
      description: 'Salah satu kebun binatang tertua dan terbesar di Asia Tenggara yang berdiri sejak 1916. Kebun Binatang Surabaya menampung lebih dari 350 spesies hewan dengan koleksi langka seperti Komodo, Harimau Sumatera, dan berbagai burung eksotis. Dengan luas 15 hektar, KBS menjadi destinasi wisata keluarga yang sangat populer dengan harga tiket terjangkau.',
      categoryId: keluarga.id,
      area: 'Surabaya Selatan',
      address: 'Jl. Setail No.1, Darmo, Wonokromo, Surabaya',
      lat: -7.2946,
      lng: 112.7358,
      openHour: '08:00',
      closeHour: '16:00',
      ticketPrice: 15000,
      mainImage: 'https://images.unsplash.com/photo-1534567110243-8875d64ca8ff?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=600&q=80',
      ]),
      rating: 4.2,
      reviewCount: 892,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 180,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Restoran', 'Toko Souvenir', 'Area Bermain Anak', 'Wahana Gajah']),
    },
    {
      name: 'Kenjeran Park (Kenpark)',
      slug: 'kenjeran-park',
      description: 'Taman hiburan dan rekreasi terpadu di tepi pantai Kenjeran dengan berbagai wahana seru. Kenpark menawarkan kombinasi wisata pantai, taman bermain, dan atraksi budaya dalam satu kawasan. Ada arena bermain anak, restoran seafood, dan area foto unik dengan background Jembatan Suramadu. Cocok untuk liburan keluarga yang mencari keseruan lengkap.',
      categoryId: keluarga.id,
      area: 'Surabaya Timur',
      address: 'Jl. Kenjeran No.1, Sukolilo, Surabaya',
      lat: -7.2214,
      lng: 112.8024,
      openHour: '07:00',
      closeHour: '21:00',
      ticketPrice: 20000,
      mainImage: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.1,
      reviewCount: 312,
      featured: false,
      hiddenGem: false,
      estimatedDuration: 150,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Restoran', 'Wahana Air', 'Area Bermain', 'Taman']),
    },
    {
      name: 'ITS (Institut Teknologi Sepuluh Nopember)',
      slug: 'its-surabaya',
      description: 'Kampus ITS dengan arsitektur megah yang menjadi salah satu spot foto terpopuler di Surabaya. Gedung Rektorat dengan kolam pantul yang memantulkan bayangan sempurna menjadi konten viral favorit. Area taman kampus yang hijau dan luas sangat nyaman untuk bersantai sambil menikmati suasana akademis yang aktif. Tersedia berbagai kantin dengan kuliner terjangkau.',
      categoryId: hiddenGem.id,
      area: 'Surabaya Timur',
      address: 'Jl. Raya ITS, Keputih, Sukolilo, Surabaya',
      lat: -7.2817,
      lng: 112.7972,
      openHour: '07:00',
      closeHour: '17:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.5,
      reviewCount: 234,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 60,
      facilities: JSON.stringify(['Parkir', 'Kantin', 'Toilet', 'Wifi', 'Taman']),
    },

    // ===== SURABAYA SELATAN =====
    {
      name: 'G-Walk Citraland',
      slug: 'g-walk-citraland',
      description: 'Kawasan kuliner dan lifestyle outdoor yang sangat populer di Surabaya Barat. G-Walk menawarkan ratusan pilihan kuliner dari berbagai penjuru dunia dalam suasana taman yang instagramable. Tempat nongkrong favorit warga Surabaya di akhir pekan dengan live music, food festival, dan berbagai event kreatif yang sering diselenggarakan.',
      categoryId: kuliner.id,
      area: 'Surabaya Barat',
      address: 'Jl. Darmo Permai III, Pradahkalikendal, Dukuhpakis, Surabaya',
      lat: -7.2983,
      lng: 112.7034,
      openHour: '10:00',
      closeHour: '22:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=600&q=80',
      ]),
      rating: 4.5,
      reviewCount: 678,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 120,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'ATM', 'Kuliner Beragam', 'Area Duduk Outdoor', 'Live Music Area']),
    },
    {
      name: 'Pasar Atom Surabaya',
      slug: 'pasar-atom-surabaya',
      description: 'Pusat perbelanjaan tradisional terbesar di Surabaya yang sudah berusia lebih dari 50 tahun. Pasar Atom menawarkan berbagai produk mulai dari fashion, aksesoris, makanan khas, hingga oleh-oleh Surabaya dengan harga yang sangat terjangkau. Kawasan ini juga dikenal sebagai pusat perdagangan tekstil dan grosir terbesar di Jawa Timur.',
      categoryId: budaya.id,
      area: 'Surabaya Pusat',
      address: 'Jl. Bunguran No.45, Bubutan, Surabaya',
      lat: -7.2443,
      lng: 112.7337,
      openHour: '08:00',
      closeHour: '21:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1493925410384-84f842d3fc5c?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.1,
      reviewCount: 234,
      featured: false,
      hiddenGem: false,
      estimatedDuration: 90,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Mushola', 'ATM', 'Food Court']),
    },
    {
      name: 'Taman Hiburan Rakyat (THR)',
      slug: 'taman-hiburan-rakyat',
      description: 'Taman hiburan legendaris Surabaya yang telah berdiri sejak era Presiden Soekarno. THR menawarkan berbagai wahana permainan, pertunjukan kesenian tradisional Jawa, dan nuansa hiburan rakyat yang autentik. Meski sudah vintage, suasana retro dan berbagai pertunjukan budaya Jawa yang rutin digelar di sini menjadikan THR pengalaman wisata yang unik.',
      categoryId: budaya.id,
      area: 'Surabaya Pusat',
      address: 'Jl. KGPAA Mangkunegara, Ketabang, Genteng, Surabaya',
      lat: -7.2544,
      lng: 112.7516,
      openHour: '17:00',
      closeHour: '23:00',
      ticketPrice: 5000,
      mainImage: 'https://images.unsplash.com/photo-1509815941021-7b4eb7fcf9e0?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 3.9,
      reviewCount: 187,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 120,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Warung Makan', 'Wahana', 'Pertunjukan Budaya']),
    },
    {
      name: 'House of Sampoerna',
      slug: 'house-of-sampoerna',
      description: 'Museum dan heritage center yang menceritakan sejarah panjang perusahaan rokok legendaris Sampoerna sejak 1913. Berlokasi di gedung bersejarah bergaya kolonial, museum ini menyajikan koleksi artefak, foto-foto antik, dan diorama proses pembuatan rokok tradisional. Area café dan toko souvenir premium di sekitar museum menambah kelengkapan pengalaman wisata ini.',
      categoryId: sejarah.id,
      area: 'Surabaya Utara',
      address: 'Jl. Taman Sampoerna No.6, Krembangan Utara, Surabaya',
      lat: -7.2383,
      lng: 112.7295,
      openHour: '09:00',
      closeHour: '18:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1568438350562-2cae6d394ad0?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1561495376-dc9c7c5b8726?w=600&q=80',
      ]),
      rating: 4.7,
      reviewCount: 678,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 90,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Kafe', 'Toko Souvenir', 'Tour Guide', 'AC']),
    },
    {
      name: 'Kebun Raya Mangrove Surabaya',
      slug: 'kebun-raya-mangrove-surabaya',
      description: 'Hutan mangrove terluas di dunia yang berada dalam kawasan kota, menjadikan Surabaya sebagai kota dengan mangrove urban terbesar. Pengunjung dapat berjalan di atas jembatan kayu sepanjang beberapa kilometer di tengah hutan bakau yang rindang. Ragam burung liar, biawak, dan satwa mangrove dapat dijumpai di sini. Sunset di tengah mangrove menjadi pengalaman magis.',
      categoryId: alam.id,
      area: 'Surabaya Timur',
      address: 'Jl. Medokan Sawah Timur, Rungkut, Surabaya',
      lat: -7.3214,
      lng: 112.8156,
      openHour: '07:00',
      closeHour: '17:00',
      ticketPrice: 10000,
      mainImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef47?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&q=80',
      ]),
      rating: 4.6,
      reviewCount: 289,
      featured: true,
      hiddenGem: false,
      estimatedDuration: 120,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Warung', 'Jembatan Kayu', 'Tour Guide', 'Spot Foto']),
    },

    // ===== KULINER =====
    {
      name: 'Rujak Cingur Ahmad Jaiz',
      slug: 'rujak-cingur-ahmad-jaiz',
      description: 'Destinasi kuliner legendaris yang menyajikan Rujak Cingur, makanan khas Surabaya paling ikonik. Rujak Cingur Ahmad Jaiz sudah berdiri puluhan tahun dan menjadi rujukan wajib bagi wisatawan yang ingin mencicipi kuliner autentik Surabaya. Cingur (hidung sapi) yang kenyal, petis udang yang pekat, dan ragam sayuran segar menciptakan harmoni rasa yang tak tertandingi.',
      categoryId: kuliner.id,
      area: 'Surabaya Pusat',
      address: 'Jl. Genteng Besar, Genteng, Surabaya',
      lat: -7.2628,
      lng: 112.7462,
      openHour: '09:00',
      closeHour: '17:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.8,
      reviewCount: 534,
      featured: false,
      hiddenGem: false,
      estimatedDuration: 45,
      facilities: JSON.stringify(['Parkir Tepi Jalan', 'Kursi & Meja']),
    },
    {
      name: 'Warung Rawon Nguling',
      slug: 'warung-rawon-nguling',
      description: 'Warung rawon paling legendaris di Surabaya yang sudah melayani pelanggan sejak 1948. Rawon hitam pekat dengan kluwek asli dan daging sapi empuk yang harum menjadi ciri khas warung ini. Selalu ramai setiap harinya, bahkan sejak pagi hari, warung ini menjadi rujukan utama para pecinta culinary heritage Surabaya termasuk banyak pejabat dan selebriti.',
      categoryId: kuliner.id,
      area: 'Surabaya Pusat',
      address: 'Jl. Irian Barat No.42, Darmo, Wonokromo, Surabaya',
      lat: -7.2897,
      lng: 112.7357,
      openHour: '06:00',
      closeHour: '15:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.9,
      reviewCount: 892,
      featured: false,
      hiddenGem: false,
      estimatedDuration: 45,
      facilities: JSON.stringify(['Parkir Terbatas', 'Kursi & Meja', 'Take Away']),
    },
    {
      name: 'Pecel Semanggi Bu Siti',
      slug: 'pecel-semanggi-bu-siti',
      description: 'Kuliner hidden gem khas Surabaya yang jarang diketahui wisatawan dari luar kota. Pecel Semanggi menggunakan daun semanggi kering yang direbus dan disajikan dengan bumbu kacang dan petis yang khas. Bu Siti sudah berjualan keliling selama puluhan tahun dan kini menetap di kawasan Jembatan Merah. Ini adalah kuliner tradisional yang terancam punah dan wajib dicicipi.',
      categoryId: kuliner.id,
      area: 'Surabaya Utara',
      address: 'Jl. Veteran, Bongkaran, Pabean Cantian, Surabaya',
      lat: -7.2319,
      lng: 112.7339,
      openHour: '07:00',
      closeHour: '14:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.6,
      reviewCount: 123,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 30,
      facilities: JSON.stringify(['Duduk di Pinggir Jalan', 'Take Away']),
    },

    // ===== SURABAYA BARAT & SELATAN =====
    {
      name: 'Danau Universitas Airlangga',
      slug: 'danau-universitas-airlangga',
      description: 'Kawasan danau alami yang tersembunyi di dalam kampus Universitas Airlangga yang hijau dan asri. Spot ini menjadi tempat favorit mahasiswa dan fotografer yang mencari ketenangan di tengah kota. Burung-burung liar sering terlihat di sekitar danau, sementara pepohonan rindang menciptakan suasana sejuk yang jauh dari hiruk-pikuk kota. Cocok untuk sesi foto atau sekadar bersantai.',
      categoryId: hiddenGem.id,
      area: 'Surabaya Pusat',
      address: 'Kampus A Universitas Airlangga, Jl. Dharmawangsa Dalam, Airlangga, Surabaya',
      lat: -7.2689,
      lng: 112.7597,
      openHour: '06:00',
      closeHour: '18:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1606117947862-d2ab3f35a3d7?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.4,
      reviewCount: 87,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 60,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Kantin Kampus']),
    },
    {
      name: 'Surabaya North Quay',
      slug: 'surabaya-north-quay',
      description: 'Destinasi wisata pelabuhan premium di Terminal Gapura Surya Nusantara yang menawarkan pemandangan laut dan kapal pesiar yang menakjubkan. Dengan berbagai spot foto instagramable, kafe dengan view Selat Madura, dan area waterfront modern, Surabaya North Quay menjadi destinasi wajib untuk menikmati sisi modern Surabaya. Atap gedung menawarkan panorama 360 derajat kota dan laut.',
      categoryId: hiddenGem.id,
      area: 'Surabaya Utara',
      address: 'Terminal Penumpang Pelabuhan Tanjung Perak, Surabaya',
      lat: -7.1987,
      lng: 112.7301,
      openHour: '10:00',
      closeHour: '21:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800&q=80',
      gallery: JSON.stringify([
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
      ]),
      rating: 4.5,
      reviewCount: 198,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 90,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Kafe & Restoran', 'Area Foto', 'Roof Deck']),
    },
    {
      name: 'Museum Pendidikan Surabaya',
      slug: 'museum-pendidikan-surabaya',
      description: 'Museum unik yang menyimpan ribuan koleksi peralatan pendidikan Indonesia dari era kolonial hingga modern. Berlokasi di gedung sekolah HBS bersejarah yang dibangun tahun 1878, museum ini merupakan salah satu gedung tertua di Surabaya yang masih berdiri tegak. Koleksi buku pelajaran, alat tulis, seragam, dan peralatan sekolah tempo dulu menciptakan perjalanan nostalgia yang menarik.',
      categoryId: sejarah.id,
      area: 'Surabaya Pusat',
      address: 'Jl. Genteng Kali No.10, Genteng, Surabaya',
      lat: -7.2621,
      lng: 112.7437,
      openHour: '09:00',
      closeHour: '16:00',
      ticketPrice: 5000,
      mainImage: 'https://images.unsplash.com/photo-1568438350562-2cae6d394ad0?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.3,
      reviewCount: 89,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 60,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Panduan Tur']),
    },
    {
      name: 'Taman Mundu',
      slug: 'taman-mundu',
      description: 'Salah satu taman kota tersembunyi yang menjadi oasis hijau di tengah Surabaya Timur. Taman Mundu dilengkapi dengan kolam ikan, taman bunga, jogging track, dan fasilitas olahraga yang terawat baik. Berbeda dari taman-taman populer Surabaya, Taman Mundu menawarkan ketenangan dan suasana santai yang lebih autentik bagi warga lokal yang mencari tempat relaksasi.',
      categoryId: hiddenGem.id,
      area: 'Surabaya Timur',
      address: 'Jl. Ahmad Yani No.1, Gayungan, Surabaya',
      lat: -7.3103,
      lng: 112.7529,
      openHour: '06:00',
      closeHour: '21:00',
      ticketPrice: 0,
      mainImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      gallery: JSON.stringify([]),
      rating: 4.2,
      reviewCount: 56,
      featured: false,
      hiddenGem: true,
      estimatedDuration: 60,
      facilities: JSON.stringify(['Parkir', 'Toilet', 'Jogging Track', 'Area Olahraga', 'Kolam Ikan']),
    },
  ]

  for (const dest of destinations) {
    await prisma.destination.upsert({
      where: { slug: dest.slug },
      update: {},
      create: dest,
    })
    console.log(`  ✓ ${dest.name}`)
  }

  console.log(`✅ ${destinations.length} destinations seeded`)
  console.log('\n🎉 Seeding completed!')
  console.log('\n📌 Demo credentials:')
  console.log('   Admin: admin@mlakoow.com / admin123')
  console.log('   User:  demo@mlakoow.com / demo123')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
